#!/usr/bin/env bash
# Generates the initial Prisma migration from schema.prisma WITHOUT needing a live
# database, then appends the hand-written PostGIS / integrity SQL.
# Usage: bash scripts/db/create-init-migration.sh
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
API="$ROOT/apps/api"
NAME="20260902120000_init"
DIR="$API/prisma/migrations/$NAME"

if [ -d "$DIR" ]; then
  echo "Migration $NAME already exists — nothing to do."
  exit 0
fi

mkdir -p "$DIR"
cd "$API"
pnpm exec prisma migrate diff \
  --from-empty \
  --to-schema-datamodel prisma/schema.prisma \
  --script > "$DIR/migration.sql"

{
  echo ""
  echo "-- ===================== hand-written additions ====================="
  cat prisma/sql/001_postgis_triggers_and_integrity.sql
} >> "$DIR/migration.sql"

cat > "$API/prisma/migrations/migration_lock.toml" <<'LOCK'
# Please do not edit this file manually
# It should be added in your version-control system (i.e. Git)
provider = "postgresql"
LOCK

echo "Created $DIR/migration.sql ($(wc -l < "$DIR/migration.sql") lines)."
echo "Next: pnpm --filter @tamam/api prisma:migrate:dev"
