#!/usr/bin/env bash
# =====================================================================
# TAMAM — uploads the placeholder creatives generated by `prisma/seed.ts`
# into the object store, so the seeded MediaAsset rows resolve to real bytes.
#
#   bash scripts/seed-assets.sh
#
# Reads S3_* from apps/api/.env (or the environment). Uses the `mc` MinIO
# client when available and falls back to signed `curl` PUT requests.
# Idempotent: re-uploading overwrites the same object keys.
# =====================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ASSETS_DIR="$ROOT/infrastructure/docker/seed-assets"
ENV_FILE="${ENV_FILE:-$ROOT/apps/api/.env}"

if [ -f "$ENV_FILE" ]; then
  # shellcheck disable=SC1090
  set -a; . "$ENV_FILE"; set +a
fi

S3_ENDPOINT="${S3_ENDPOINT:-http://localhost:9000}"
S3_ACCESS_KEY="${S3_ACCESS_KEY:-tamam}"
S3_SECRET_KEY="${S3_SECRET_KEY:-tamam-secret}"
S3_REGION="${S3_REGION:-us-east-1}"
S3_BUCKET_PUBLIC="${S3_BUCKET_PUBLIC:-tamam-public}"
S3_BUCKET_PRIVATE="${S3_BUCKET_PRIVATE:-tamam-private}"

if [ ! -d "$ASSETS_DIR" ]; then
  echo "No generated assets in $ASSETS_DIR — run 'pnpm --filter @tamam/api seed' first." >&2
  exit 1
fi

# local relative path : bucket : object key
MANIFEST="
banners/home-hero-ar.png:$S3_BUCKET_PUBLIC:seed/banners/home-hero-ar.png
banners/home-hero-en.png:$S3_BUCKET_PUBLIC:seed/banners/home-hero-en.png
banners/home-inline.png:$S3_BUCKET_PUBLIC:seed/banners/home-inline.png
documents/placeholder.png:$S3_BUCKET_PRIVATE:seed/documents/placeholder.png
"

upload_with_mc() {
  mc alias set tamam-seed "$S3_ENDPOINT" "$S3_ACCESS_KEY" "$S3_SECRET_KEY" >/dev/null
  mc mb --ignore-existing "tamam-seed/$S3_BUCKET_PUBLIC" >/dev/null
  mc mb --ignore-existing "tamam-seed/$S3_BUCKET_PRIVATE" >/dev/null
  mc anonymous set download "tamam-seed/$S3_BUCKET_PUBLIC" >/dev/null
  echo "$MANIFEST" | while IFS=: read -r rel bucket key; do
    [ -n "$rel" ] || continue
    mc cp --attr "Content-Type=image/png" "$ASSETS_DIR/$rel" "tamam-seed/$bucket/$key" >/dev/null
    echo "  uploaded $bucket/$key"
  done
}

# Minimal AWS Signature V4 PUT — no dependency beyond curl + openssl.
put_signed() {
  local file="$1" bucket="$2" key="$3"
  local host date_stamp amz_date payload_hash canonical_request string_to_sign
  local k_date k_region k_service k_signing signature
  host="$(printf '%s' "$S3_ENDPOINT" | sed -E 's#^https?://##')"
  amz_date="$(date -u +%Y%m%dT%H%M%SZ)"
  date_stamp="$(date -u +%Y%m%d)"
  payload_hash="$(openssl dgst -sha256 -hex < "$file" | awk '{print $NF}')"

  canonical_request="PUT
/$bucket/$key

content-type:image/png
host:$host
x-amz-content-sha256:$payload_hash
x-amz-date:$amz_date

content-type;host;x-amz-content-sha256;x-amz-date
$payload_hash"

  string_to_sign="AWS4-HMAC-SHA256
$amz_date
$date_stamp/$S3_REGION/s3/aws4_request
$(printf '%s' "$canonical_request" | openssl dgst -sha256 -hex | awk '{print $NF}')"

  k_date="$(printf '%s' "$date_stamp" | openssl dgst -sha256 -mac HMAC -macopt "key:AWS4$S3_SECRET_KEY" -hex | awk '{print $NF}')"
  k_region="$(printf '%s' "$S3_REGION" | openssl dgst -sha256 -mac HMAC -macopt "hexkey:$k_date" -hex | awk '{print $NF}')"
  k_service="$(printf '%s' 's3' | openssl dgst -sha256 -mac HMAC -macopt "hexkey:$k_region" -hex | awk '{print $NF}')"
  k_signing="$(printf '%s' 'aws4_request' | openssl dgst -sha256 -mac HMAC -macopt "hexkey:$k_service" -hex | awk '{print $NF}')"
  signature="$(printf '%s' "$string_to_sign" | openssl dgst -sha256 -mac HMAC -macopt "hexkey:$k_signing" -hex | awk '{print $NF}')"

  curl -sS -f -X PUT "$S3_ENDPOINT/$bucket/$key" \
    -H "Content-Type: image/png" \
    -H "x-amz-content-sha256: $payload_hash" \
    -H "x-amz-date: $amz_date" \
    -H "Authorization: AWS4-HMAC-SHA256 Credential=$S3_ACCESS_KEY/$date_stamp/$S3_REGION/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=$signature" \
    --data-binary "@$file" >/dev/null
}

upload_with_curl() {
  echo "$MANIFEST" | while IFS=: read -r rel bucket key; do
    [ -n "$rel" ] || continue
    put_signed "$ASSETS_DIR/$rel" "$bucket" "$key"
    echo "  uploaded $bucket/$key"
  done
}

echo "Uploading seed assets to $S3_ENDPOINT"
if command -v mc >/dev/null 2>&1; then
  upload_with_mc
else
  command -v curl >/dev/null 2>&1 || { echo "neither 'mc' nor 'curl' is available" >&2; exit 1; }
  command -v openssl >/dev/null 2>&1 || { echo "openssl is required for the curl fallback" >&2; exit 1; }
  upload_with_curl
fi
echo "Done. Public creatives: ${S3_PUBLIC_BASE_URL:-$S3_ENDPOINT/$S3_BUCKET_PUBLIC}/seed/banners/"
